# Generated by Django 4.1.5 on 2023-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateTimeField()),
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
